In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_auc_score
from functions.GINI import gini_xgb
from functions.PSI import calculate_psi
import xgboost as xgb
import optuna

# Model tuning

In [34]:
df_train = pd.read_csv('df_train_op_1.csv',sep=',').reset_index(drop=True)
df_test = pd.read_csv('df_test_op_1.csv',sep=',').reset_index(drop=True)
df_val = pd.read_csv('df_val_op_1.csv',sep=',').reset_index(drop=True)

In [35]:
df_train.columns.tolist()

['MAKH',
 'DATEIN_DATE',
 'MONTHIN',
 'TAG_GB',
 'CNT_COLLATERAL_HCM_QSDD',
 'AVG_LTV_L3M',
 'ca_over_1m_l1m_ct_l3m',
 'ca_min_l12m',
 'sa_min_l12m',
 'sa_median_l12m',
 'casa_min_l12m',
 'sa_min_l6m',
 'casa_min_l6m_ct_l12m',
 'casa_q25_l6m_ct_l12m',
 'casa_median_l6m_ct_l12m',
 'ca_q75_l6m_ct_l12m',
 'EMPLOYMENT_STATUS',
 'dpd_iqr_l3m',
 'dpd_min_l12m',
 'dpd_max_l12m',
 'n_dpd_1_30_l3m',
 'cons_delq_0_l3m',
 'cons_delq_90_l3m',
 'cons_delq_increase_l6m',
 'cons_delq_90_l12m',
 'days_last_ptp_l1m',
 'DIA_CHI']

In [36]:
len(df_train.columns)-4

23

In [37]:
x_train = df_train.loc[:,[col for col in df_train.columns if not col in ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']]]
x_test = df_test.loc[:,[col for col in df_test.columns if not col in ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']]]
x_val = df_val.loc[:,[col for col in df_val.columns if not col in ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']]]

y_train = df_train.loc[:, ['TAG_GB']]
y_test = df_test.loc[:, ['TAG_GB']]
y_val = df_val.loc[:, ['TAG_GB']]

d_train = xgb.DMatrix(x_train, y_train, enable_categorical=True, missing = np.nan)
d_test = xgb.DMatrix(x_test, y_test, enable_categorical=True, missing = np.nan)
d_val = xgb.DMatrix(x_val, y_val, enable_categorical=True, missing = np.nan)

In [39]:
def objective(trial):
    fixed_params = {
        'objective' : 'binary:logistic',
        'random_state' : 42,
        'seed' : 27,
        'nthread': 10
    }
        
    params = {
            'gamma': trial.suggest_float('gamma', 0.5, 8.0),
            'subsample': trial.suggest_float('subsample', 0.5, 0.7),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 0.7),
            'max_depth': trial.suggest_int('max_depth', 4, 6),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
            'n_estimators': trial.suggest_int('n_estimators', 300, 900),
            'eta': trial.suggest_float('eta', 0.01, 0.04),
            'lambda': trial.suggest_float('lambda', 0.5, 5),
            'alpha': trial.suggest_float('alpha', 0.0, 2.0),
            'max_delta_step': trial.suggest_int('max_delta_step', 0, 10)
        }

    params_final = {**fixed_params, **params}

    bst = xgb.train(
            {key: value for key, value in params_final.items() if key != 'n_estimators'},
            dtrain = d_train,
            num_boost_round=params_final['n_estimators']
    )

    train_gini = gini_xgb(bst.predict(d_train),d_train)[1]
    val_gini = gini_xgb(bst.predict(d_val),d_val)[1]

    gini_diff = abs(train_gini - val_gini)

    gini_diff_penalty = 1000 if gini_diff > 0.05 else 0

    gini_below_threshold_penalty = 1000 if (train_gini < 0.30 or val_gini < 0.30) else 0

    gini_diff_penalty += gini_diff_penalty
    gini_below_threshold_penalty += gini_below_threshold_penalty

    weight_test_gini = 1.0  
    weight_gini_diff = 1  
    weight_gini_below_threshold = 1

    objective_value = -weight_test_gini * val_gini + weight_gini_diff * gini_diff_penalty + weight_gini_below_threshold * gini_below_threshold_penalty
    return objective_value

study = optuna.create_study(direction='minimize') 
study.optimize(objective, n_trials=100)

print("Best trial:")
print(study.best_trial.params)
print(f"Best objective value: {study.best_value}")

[I 2025-06-19 14:03:11,498] A new study created in memory with name: no-name-0afc4815-c87e-451f-b1d3-c981283a8af2
[I 2025-06-19 14:03:16,663] Trial 0 finished with value: 1999.3224810462905 and parameters: {'gamma': 0.991334652951487, 'subsample': 0.5267518826728101, 'colsample_bytree': 0.533408742366661, 'max_depth': 6, 'min_child_weight': 2, 'n_estimators': 435, 'eta': 0.012642822022624232, 'lambda': 4.600163200061577, 'alpha': 1.0671108233299074, 'max_delta_step': 0}. Best is trial 0 with value: 1999.3224810462905.
[I 2025-06-19 14:03:19,616] Trial 1 finished with value: 1999.3195777100539 and parameters: {'gamma': 2.650215832364538, 'subsample': 0.5704606019515204, 'colsample_bytree': 0.6719874758759171, 'max_depth': 4, 'min_child_weight': 10, 'n_estimators': 351, 'eta': 0.03435973035794833, 'lambda': 2.1202259809051944, 'alpha': 0.384026064353173, 'max_delta_step': 8}. Best is trial 1 with value: 1999.3195777100539.
[I 2025-06-19 14:03:22,807] Trial 2 finished with value: -0.666357390166914 and parameters: {'gamma': 5.5883628700414745, 'subsample': 0.5008930386170989, 'colsample_bytree': 0.5628760037335924, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 408, 'eta': 0.02399647101625045, 'lambda': 0.7211302350876236, 'alpha': 0.40399406704915886, 'max_delta_step': 5}. Best is trial 2 with value: -0.666357390166914.
[I 2025-06-19 14:03:26,090] Trial 3 finished with value: -0.669122431027193 and parameters: {'gamma': 4.9287390732977965, 'subsample': 0.6281565095411317, 'colsample_bytree': 0.5299015381737657, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 397, 'eta': 0.027947637339838072, 'lambda': 2.962423639128027, 'alpha': 0.9520039848421349, 'max_delta_step': 5}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:03:33,876] Trial 4 finished with value: 1999.309180175847 and parameters: {'gamma': 3.0002770496294597, 'subsample': 0.6708138153928361, 'colsample_bytree': 0.5056592222390468, 'max_depth': 5, 'min_child_weight': 10, 'n_estimators': 844, 'eta': 0.01777795251105877, 'lambda': 3.345891047037698, 'alpha': 0.8507399034570289, 'max_delta_step': 7}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:03:43,581] Trial 5 finished with value: 1999.3031773888918 and parameters: {'gamma': 2.500181755546418, 'subsample': 0.5369731549855168, 'colsample_bytree': 0.6012327502441628, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 697, 'eta': 0.015288013472861583, 'lambda': 3.785152897498601, 'alpha': 1.4613399662964182, 'max_delta_step': 8}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:03:48,547] Trial 6 finished with value: -0.6652241604622556 and parameters: {'gamma': 6.316888831000933, 'subsample': 0.5790269938992925, 'colsample_bytree': 0.5280889057762157, 'max_depth': 5, 'min_child_weight': 8, 'n_estimators': 841, 'eta': 0.024486757912259155, 'lambda': 4.592390558331729, 'alpha': 1.1646022924634862, 'max_delta_step': 6}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:03:54,579] Trial 7 finished with value: 1999.3126572459905 and parameters: {'gamma': 2.888374949700085, 'subsample': 0.6116356221829303, 'colsample_bytree': 0.5441694376751329, 'max_depth': 5, 'min_child_weight': 1, 'n_estimators': 610, 'eta': 0.015121471132011205, 'lambda': 2.0630683643089993, 'alpha': 1.574454904825571, 'max_delta_step': 8}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:04:01,272] Trial 8 finished with value: 1999.3011168249263 and parameters: {'gamma': 0.5054028401896139, 'subsample': 0.6115396256040799, 'colsample_bytree': 0.6438228123147074, 'max_depth': 5, 'min_child_weight': 10, 'n_estimators': 630, 'eta': 0.02423315834309328, 'lambda': 0.6066629243700254, 'alpha': 1.6114724764115564, 'max_delta_step': 7}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:04:04,580] Trial 9 finished with value: -0.6627862246909867 and parameters: {'gamma': 1.6138830150955985, 'subsample': 0.5900905917340911, 'colsample_bytree': 0.6473456288073228, 'max_depth': 4, 'min_child_weight': 6, 'n_estimators': 307, 'eta': 0.023135565154882895, 'lambda': 4.36693523722965, 'alpha': 1.3625578108823015, 'max_delta_step': 8}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:04:07,583] Trial 10 finished with value: -0.662989272513082 and parameters: {'gamma': 7.336068514479437, 'subsample': 0.6698208468288381, 'colsample_bytree': 0.589903197644346, 'max_depth': 4, 'min_child_weight': 4, 'n_estimators': 461, 'eta': 0.034715685673467625, 'lambda': 2.5939171079419605, 'alpha': 1.938051948606488, 'max_delta_step': 3}. Best is trial 3 with value: -0.669122431027193.
[I 2025-06-19 14:04:10,967] Trial 11 finished with value: -0.6755341612484469 and parameters: {'gamma': 5.119801593401191, 'subsample': 0.6402492386379844, 'colsample_bytree': 0.5708279509449481, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 473, 'eta': 0.030355022688950264, 'lambda': 0.9556007629482202, 'alpha': 0.27093736620109377, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:14,734] Trial 12 finished with value: 1999.323212389879 and parameters: {'gamma': 4.608406579706823, 'subsample': 0.6423655979975231, 'colsample_bytree': 0.5838528723257029, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 514, 'eta': 0.029900649972047968, 'lambda': 1.301857502184471, 'alpha': 0.0634608956099234, 'max_delta_step': 3}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:18,290] Trial 13 finished with value: 1999.3253305253306 and parameters: {'gamma': 4.480044014124416, 'subsample': 0.6377068716981779, 'colsample_bytree': 0.5632460810704804, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 526, 'eta': 0.03957273009655959, 'lambda': 3.166093008890038, 'alpha': 0.71965171065842, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:21,723] Trial 14 finished with value: -0.6711293854150999 and parameters: {'gamma': 5.49196515397888, 'subsample': 0.6429032302835979, 'colsample_bytree': 0.5000759484523352, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 528, 'eta': 0.029580273466568618, 'lambda': 1.5215136150702226, 'alpha': 0.5109820064346251, 'max_delta_step': 10}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:25,837] Trial 15 finished with value: -0.6670870004203336 and parameters: {'gamma': 7.821373539384689, 'subsample': 0.6997003523598215, 'colsample_bytree': 0.5011555725396186, 'max_depth': 5, 'min_child_weight': 6, 'n_estimators': 705, 'eta': 0.031263360638065375, 'lambda': 1.2363672396922532, 'alpha': 0.5169098587020738, 'max_delta_step': 10}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:29,016] Trial 16 finished with value: -0.6694955933051171 and parameters: {'gamma': 6.357519200122155, 'subsample': 0.6627419028620116, 'colsample_bytree': 0.6278930321737076, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 516, 'eta': 0.0392231429164227, 'lambda': 1.664860802636835, 'alpha': 0.006951319405352985, 'max_delta_step': 1}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:35,530] Trial 17 finished with value: 1999.3000764524575 and parameters: {'gamma': 3.624977982139378, 'subsample': 0.6870970619375452, 'colsample_bytree': 0.6983978916468889, 'max_depth': 6, 'min_child_weight': 9, 'n_estimators': 560, 'eta': 0.020856579428815844, 'lambda': 1.069013612057648, 'alpha': 0.22500016039631654, 'max_delta_step': 10}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:39,487] Trial 18 finished with value: 1999.3235125044648 and parameters: {'gamma': 5.8118592458717115, 'subsample': 0.6511132385804739, 'colsample_bytree': 0.6068080405411664, 'max_depth': 5, 'min_child_weight': 5, 'n_estimators': 739, 'eta': 0.027931903815511902, 'lambda': 1.7696053497962274, 'alpha': 0.645393814798946, 'max_delta_step': 2}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:43,168] Trial 19 finished with value: -0.6709951757570807 and parameters: {'gamma': 5.307875133303757, 'subsample': 0.6229009181942364, 'colsample_bytree': 0.5647179170862688, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 474, 'eta': 0.03472039304923825, 'lambda': 2.4200332015631454, 'alpha': 0.23948167189848724, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:48,150] Trial 20 finished with value: 1999.3108049298526 and parameters: {'gamma': 3.795543486656015, 'subsample': 0.5627199717409466, 'colsample_bytree': 0.5142255995548886, 'max_depth': 5, 'min_child_weight': 9, 'n_estimators': 590, 'eta': 0.0326712917422146, 'lambda': 1.5756535673304128, 'alpha': 0.6305380525761493, 'max_delta_step': 6}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:51,052] Trial 21 finished with value: -0.6711058615820521 and parameters: {'gamma': 5.324083892066081, 'subsample': 0.6206888224095007, 'colsample_bytree': 0.5594161047921304, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 475, 'eta': 0.03679933008558641, 'lambda': 2.352409273847126, 'alpha': 0.2358627199344812, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:54,209] Trial 22 finished with value: -0.6632914918629205 and parameters: {'gamma': 6.805133339166449, 'subsample': 0.5950342293917433, 'colsample_bytree': 0.5508639091009532, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 374, 'eta': 0.036455843350150376, 'lambda': 2.0336104254931078, 'alpha': 0.20697478245098244, 'max_delta_step': 3}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:04:59,278] Trial 23 finished with value: 1999.3224777034302 and parameters: {'gamma': 3.9770207923727323, 'subsample': 0.6539573244563486, 'colsample_bytree': 0.582852497138448, 'max_depth': 4, 'min_child_weight': 6, 'n_estimators': 470, 'eta': 0.029342786901319924, 'lambda': 0.9373948497810201, 'alpha': 0.38337035914323014, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:04,653] Trial 24 finished with value: 1999.3269934127077 and parameters: {'gamma': 5.2982995936573705, 'subsample': 0.6118343043946418, 'colsample_bytree': 0.62046144316347, 'max_depth': 4, 'min_child_weight': 9, 'n_estimators': 652, 'eta': 0.02751089905053941, 'lambda': 1.381014312275663, 'alpha': 0.5259520128402762, 'max_delta_step': 2}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:07,890] Trial 25 finished with value: -0.667170819551772 and parameters: {'gamma': 6.1817506581301185, 'subsample': 0.6319423357598902, 'colsample_bytree': 0.5697466023694391, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 562, 'eta': 0.03786732983952989, 'lambda': 2.4066204231586394, 'alpha': 0.1739173460740288, 'max_delta_step': 6}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:10,745] Trial 26 finished with value: 1999.3249594678166 and parameters: {'gamma': 4.869631437646604, 'subsample': 0.6846477185649367, 'colsample_bytree': 0.5180616818493314, 'max_depth': 4, 'min_child_weight': 4, 'n_estimators': 495, 'eta': 0.03233452288681228, 'lambda': 0.5390551049532166, 'alpha': 0.8016970847906775, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:13,443] Trial 27 finished with value: -0.666972476496286 and parameters: {'gamma': 6.998988400013944, 'subsample': 0.6461974396451001, 'colsample_bytree': 0.5464031542282575, 'max_depth': 5, 'min_child_weight': 7, 'n_estimators': 336, 'eta': 0.03657692469112951, 'lambda': 1.8674910988336808, 'alpha': 0.4908407753529662, 'max_delta_step': 9}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:16,458] Trial 28 finished with value: -0.6678406297453917 and parameters: {'gamma': 5.86893590600186, 'subsample': 0.6189659839110446, 'colsample_bytree': 0.577689890357613, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 412, 'eta': 0.02621497662531954, 'lambda': 0.8940349054532353, 'alpha': 0.32848257872336717, 'max_delta_step': 2}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:20,264] Trial 29 finished with value: -0.6634711396616159 and parameters: {'gamma': 5.1422123202364585, 'subsample': 0.5556345135732218, 'colsample_bytree': 0.5358256190443083, 'max_depth': 4, 'min_child_weight': 9, 'n_estimators': 450, 'eta': 0.021509415506558105, 'lambda': 3.523200816285259, 'alpha': 1.1068755465035751, 'max_delta_step': 0}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:24,151] Trial 30 finished with value: 1999.3299259680211 and parameters: {'gamma': 6.832721726504002, 'subsample': 0.5993674004312394, 'colsample_bytree': 0.6172658814571648, 'max_depth': 6, 'min_child_weight': 6, 'n_estimators': 551, 'eta': 0.03045713365899372, 'lambda': 2.7337926065986875, 'alpha': 0.09956826911332683, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:26,881] Trial 31 finished with value: -0.6726214154785582 and parameters: {'gamma': 5.5170846679805825, 'subsample': 0.6248367598581948, 'colsample_bytree': 0.5526476674028459, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 481, 'eta': 0.03404745012425246, 'lambda': 2.3969633006632227, 'alpha': 0.25175921378450367, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:29,952] Trial 32 finished with value: 1999.3223368080512 and parameters: {'gamma': 4.125782014328572, 'subsample': 0.6588476575294003, 'colsample_bytree': 0.556429122637622, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 434, 'eta': 0.03364380392010225, 'lambda': 2.262885381138741, 'alpha': 0.307657671510643, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:33,984] Trial 33 finished with value: -0.6697085458990221 and parameters: {'gamma': 5.654825395237614, 'subsample': 0.637488205676533, 'colsample_bytree': 0.5382914775586254, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 491, 'eta': 0.031865950774002796, 'lambda': 2.8977421478966865, 'alpha': 0.4412005888853489, 'max_delta_step': 3}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:37,978] Trial 34 finished with value: 1999.3262553833983 and parameters: {'gamma': 4.652726516208383, 'subsample': 0.5877591433319826, 'colsample_bytree': 0.522022325771393, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 416, 'eta': 0.03612520652609394, 'lambda': 1.5925505028125195, 'alpha': 0.14624158891489142, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:41,942] Trial 35 finished with value: -0.6740266549790358 and parameters: {'gamma': 5.403919366391022, 'subsample': 0.6232067112022477, 'colsample_bytree': 0.5920856800426416, 'max_depth': 4, 'min_child_weight': 6, 'n_estimators': 545, 'eta': 0.029111032094833175, 'lambda': 1.9689962208975342, 'alpha': 0.28714660748558885, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:46,993] Trial 36 finished with value: 1999.315980173123 and parameters: {'gamma': 3.3984205496912168, 'subsample': 0.628404419157535, 'colsample_bytree': 0.5927225289024722, 'max_depth': 4, 'min_child_weight': 4, 'n_estimators': 585, 'eta': 0.026743947653343526, 'lambda': 1.9244939560151764, 'alpha': 0.9606863772312902, 'max_delta_step': 7}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:50,660] Trial 37 finished with value: -0.6639513972847307 and parameters: {'gamma': 6.087867523283781, 'subsample': 0.5011576901829148, 'colsample_bytree': 0.5747301986855508, 'max_depth': 4, 'min_child_weight': 6, 'n_estimators': 381, 'eta': 0.028820267057338624, 'lambda': 1.4312155003517524, 'alpha': 0.6145669789666375, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:55,193] Trial 38 finished with value: 1999.3135205706635 and parameters: {'gamma': 4.357986159234766, 'subsample': 0.6046989398636173, 'colsample_bytree': 0.5944001808263473, 'max_depth': 5, 'min_child_weight': 5, 'n_estimators': 540, 'eta': 0.02577522097441343, 'lambda': 1.1154241419344104, 'alpha': 0.3532463979703233, 'max_delta_step': 6}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:05:59,333] Trial 39 finished with value: 1999.3215310548644 and parameters: {'gamma': 5.051257873251228, 'subsample': 0.6763100423112238, 'colsample_bytree': 0.6092426155447936, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 660, 'eta': 0.03346916755299565, 'lambda': 0.7774195332984939, 'alpha': 0.7709458668457572, 'max_delta_step': 9}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:04,101] Trial 40 finished with value: -0.6689109641490595 and parameters: {'gamma': 6.514821926229419, 'subsample': 0.5818701465994943, 'colsample_bytree': 0.5295082606707765, 'max_depth': 5, 'min_child_weight': 10, 'n_estimators': 778, 'eta': 0.030693134257790737, 'lambda': 2.212980246656417, 'alpha': 0.9080661307141086, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:07,536] Trial 41 finished with value: -0.6690497547640404 and parameters: {'gamma': 5.4952317309398415, 'subsample': 0.6252381948005824, 'colsample_bytree': 0.5544727416605998, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 502, 'eta': 0.03581403364056357, 'lambda': 2.438795320148698, 'alpha': 0.27749624532856243, 'max_delta_step': 4}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:11,246] Trial 42 finished with value: -0.651441175250699 and parameters: {'gamma': 4.879311378008143, 'subsample': 0.6093655073299735, 'colsample_bytree': 0.5089429212828005, 'max_depth': 4, 'min_child_weight': 6, 'n_estimators': 437, 'eta': 0.011922984992431721, 'lambda': 2.986989750623194, 'alpha': 0.419523820287012, 'max_delta_step': 3}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:14,619] Trial 43 finished with value: 1999.3290607862036 and parameters: {'gamma': 5.486822837983689, 'subsample': 0.6185738289095393, 'colsample_bytree': 0.5722280289405831, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 612, 'eta': 0.03763369505137553, 'lambda': 2.1238056442234883, 'alpha': 0.07020085558962508, 'max_delta_step': 6}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:19,636] Trial 44 finished with value: -0.6730854540378349 and parameters: {'gamma': 6.0039417315251535, 'subsample': 0.6414313328097825, 'colsample_bytree': 0.6364768270753315, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 883, 'eta': 0.03460658606838279, 'lambda': 1.8788760753391447, 'alpha': 0.016346159589486597, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:24,005] Trial 45 finished with value: -0.6712879855737 and parameters: {'gamma': 7.366103777309879, 'subsample': 0.6445989206528633, 'colsample_bytree': 0.6563242464281683, 'max_depth': 4, 'min_child_weight': 8, 'n_estimators': 889, 'eta': 0.028905743395857608, 'lambda': 1.5271688846288574, 'alpha': 0.006201614801496733, 'max_delta_step': 7}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:28,236] Trial 46 finished with value: -0.671705100276529 and parameters: {'gamma': 7.607466254040339, 'subsample': 0.6354518171019814, 'colsample_bytree': 0.6641599288363887, 'max_depth': 4, 'min_child_weight': 9, 'n_estimators': 892, 'eta': 0.034365409814249626, 'lambda': 1.7795673402559096, 'alpha': 0.0178186589718782, 'max_delta_step': 7}. Best is trial 11 with value: -0.6755341612484469.
[I 2025-06-19 14:06:32,441] Trial 47 finished with value: -0.6656925323591991 and parameters: {'gamma': 7.9264556051702675, 'subsample': 0.6640408211451453, 'colsample_bytree': 0.682159579543903, 'max_depth': 4, 'min_child_weight': 9, 'n_estimators': 822, 'eta': 0.0345593247644624, 'lambda': 2.631352477499506, 'alpha': 0.09777511503367456, 'max_delta_step': 5}. Best is trial 11 with value: -0.6755341612484469.

Best trial:
{'gamma': 5.119801593401191, 'subsample': 0.6402492386379844, 'colsample_bytree': 0.5708279509449481, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 473, 'eta': 0.030355022688950264, 'lambda': 0.9556007629482202, 'alpha': 0.27093736620109377, 'max_delta_step': 4}
Best objective value: -0.6755341612484469

In [40]:
params_final = {
   'gamma': 5.119801593401191, 'subsample': 0.6402492386379844, 'colsample_bytree': 0.5708279509449481, 'max_depth': 4, 'min_child_weight': 7, 'n_estimators': 473, 'eta': 0.030355022688950264, 'lambda': 0.9556007629482202, 'alpha': 0.27093736620109377, 'max_delta_step': 4,
    'objective' : 'binary:logistic',
    'random_state' : 42,
    'seed' : 27,
    'nthread': 10
}

bst = xgb.train(
            {key: value for key, value in params_final.items() if key != 'n_estimators'},
            dtrain = d_train,
            num_boost_round=params_final['n_estimators']
    )

train_gini = gini_xgb(bst.predict(d_train),d_train)[1]
val_gini = gini_xgb(bst.predict(d_val),d_val)[1]
test_gini = gini_xgb(bst.predict(d_test),d_test)[1]
gini_diff = abs(train_gini - val_gini)

print('Train GINI: {}'.format(train_gini))
print('Val GINI: {}'.format(val_gini))
print('GINI drop: {}'.format(gini_diff))
print('Test GINI: {}'.format(test_gini))

Train GINI: 0.7247412080538185
Val GINI: 0.6755341612484469
GINI drop: 0.04920704680537158
Test GINI: 0.6629815811640907

In [7]:
bst.save_model('recovery_unsecured_dpd361_all_in_one_mob3_28fea.json')

In [41]:
feature_important_weight = bst.get_score(importance_type='weight')
feature_important_gain = bst.get_score(importance_type='gain')
feature_important_cover = bst.get_score(importance_type='cover')

keys = list(feature_important_weight.keys())
weight = list(feature_important_weight.values())
gain = list(feature_important_gain.values())
cover = list(feature_important_cover.values())

fs_df = pd.DataFrame(data={'feature':keys, "weight":weight, 'gain':gain, 'cover':cover})

fs_df.to_csv('feature_importance.csv',index=False)

## Score scaling

In [43]:
train_predict = bst.predict(d_train)
val_predict = bst.predict(d_val)
test_predict = bst.predict(d_test)

In [44]:
train_predict_df = pd.DataFrame(train_predict, columns=['proba'])
val_predict_df = pd.DataFrame(val_predict, columns=['proba'])
test_predict_df = pd.DataFrame(test_predict, columns=['proba'])

In [45]:
df_train = df_train.merge(train_predict_df,left_index=True,right_index=True)
df_val = df_val.merge(val_predict_df,left_index=True,right_index=True)
df_test = df_test.merge(test_predict_df,left_index=True,right_index=True)

In [46]:
pdo = 50
base_score = 500
factor = pdo/np.log(2)
offset = base_score - (factor*np.log(50))

df_train['score'] = df_train['proba'].apply(lambda x: offset + factor*np.log((1-x)/x))
df_val['score'] = df_val['proba'].apply(lambda x: offset + factor*np.log((1-x)/x))
df_test['score'] = df_test['proba'].apply(lambda x: offset + factor*np.log((1-x)/x))

## Model evaluation

### GINI

In [13]:
# Train GINI: 0.7566487786252415
# Val GINI: 0.7080419950061044
# GINI drop: 0.04860678361913706
# Test GINI: 0.6660621393218441

### KS

In [47]:
from functions.KS import calculate_ks_statistic

print('Train KS: {}'.format(calculate_ks_statistic(df_train.score, df_train.TAG_GB)))
print('Val KS: {}'.format(calculate_ks_statistic(df_val.score, df_val.TAG_GB)))
print('Test KS: {}'.format(calculate_ks_statistic(df_test.score, df_test.TAG_GB)))

Train KS: 0.5637534742320187
Val KS: 0.5185387613959043
Test KS: 0.5044412386696242

### PSI

In [48]:
df_train['score_bin']=pd.qcut(df_train.score, 10)

In [49]:
deciles, bin_edges = pd.qcut(df_train.score, 10, retbins=True)

df_val['score_bin'] = pd.cut(df_val.score, bins=bin_edges)
df_test['score_bin'] = pd.cut(df_test.score, bins=bin_edges)

In [50]:
#Calculate bad rate and odd for training set
train_pivot = df_train.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
train_pivot['BAD_RATE'] = train_pivot[1]/(train_pivot[1]+train_pivot[0])
train_pivot['ODD'] = train_pivot[1]/train_pivot[0]

#Calculate bad rate and odd for validating set
val_pivot = df_val.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
val_pivot['BAD_RATE'] = val_pivot[1]/(val_pivot[1]+val_pivot[0])
val_pivot['ODD'] = val_pivot[1]/val_pivot[0]

#Calculate bad rate and odd for testing set
test_pivot = df_test.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
test_pivot['BAD_RATE'] = test_pivot[1]/(test_pivot[1]+test_pivot[0])
test_pivot['ODD'] = test_pivot[1]/test_pivot[0]

train_pivot['DIS']=(train_pivot[0]+train_pivot[1])/(train_pivot[0].sum()+train_pivot[1].sum())
val_pivot['DIS']=(val_pivot[0]+val_pivot[1])/(val_pivot[0].sum()+val_pivot[1].sum())
test_pivot['DIS']=(test_pivot[0]+test_pivot[1])/(test_pivot[0].sum()+test_pivot[1].sum())

#Calculate PSI
train_pivot_sub = train_pivot.loc[:,'DIS']
val_pivot_sub = val_pivot.loc[:,'DIS']
test_pivot_sub = test_pivot.loc[:,'DIS']

train_val = pd.merge(train_pivot_sub,val_pivot_sub,how='inner', left_index=True, right_index=True, suffixes=['_train','_validation'])
train_val['PSI'] = (train_val['DIS_train'] - train_val['DIS_validation'])*np.log(train_val['DIS_train']/train_val['DIS_validation'])

train_test = pd.merge(train_pivot_sub,test_pivot_sub,how='inner', left_index=True, right_index=True, suffixes=['_train','_validation'])
train_test['PSI'] = (train_test['DIS_train'] - train_test['DIS_validation'])*np.log(train_test['DIS_train']/train_test['DIS_validation'])

print('PSI (train vs val): {}'.format(train_val['PSI'].sum()))
print('PSI (train vs test): {}'.format(train_test['PSI'].sum()))

PSI (train vs val): 0.0001954001037524547
PSI (train vs test): 0.0019154400263171783

/tmp/ipykernel_7775/1101814837.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  train_pivot = df_train.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/1101814837.py:7: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  val_pivot = df_val.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/1101814837.py:12: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  test_pivot = df_test.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)

In [51]:
#Calculate bad rate and odd for training set
train_pivot = df_train.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
train_pivot['BAD_RATE'] = train_pivot[1]/(train_pivot[1]+train_pivot[0])
train_pivot['ODD'] = train_pivot[1]/train_pivot[0]
train_pivot['DIS']=(train_pivot[0]+train_pivot[1])/(train_pivot[0].sum()+train_pivot[1].sum())
train_pivot_sub = train_pivot.loc[:,'DIS']

for i in df_test.MONTHIN.unique():
    df_test_sub = df_test.loc[df_test.MONTHIN==i,:]

    test_pivot = df_test_sub.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
    test_pivot['BAD_RATE'] = test_pivot[1]/(test_pivot[1]+test_pivot[0])
    test_pivot['ODD'] = test_pivot[1]/test_pivot[0]

    test_pivot['DIS']=(test_pivot[0]+test_pivot[1])/(test_pivot[0].sum()+test_pivot[1].sum())
    test_pivot_sub = test_pivot.loc[:,'DIS']

    train_test = pd.merge(train_pivot_sub,test_pivot_sub,how='inner', left_index=True, right_index=True, suffixes=['_train','_validation'])
    train_test['PSI'] = (train_test['DIS_train'] - train_test['DIS_validation'])*np.log(train_test['DIS_train']/train_test['DIS_validation'])

    print('Test month: {}, PSI: {}'.format(i, train_test['PSI'].sum()))

Test month: 202410, PSI: 0.005420559858155409
Test month: 202501, PSI: 0.0030130683125873304
Test month: 202411, PSI: 0.0017975688257168443
Test month: 202412, PSI: 0.002946925568796827

/tmp/ipykernel_7775/559348544.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  train_pivot = df_train.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/559348544.py:11: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  test_pivot = df_test_sub.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/559348544.py:11: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  test_pivot = df_test_sub.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/559348544.py:11: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  test_pivot = df_test_sub.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
/tmp/ipykernel_7775/559348544.py:11: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  test_pivot = df_test_sub.pivot_table(index='score_bin', columns='TAG_GB', aggfunc='size', fill_value=0)

In [49]:
df_train

,DATEIN_DATE,MONTHIN,TAG_GB,AVG_LTV_L3M,ca_over_1m_l1m_ct_l3m,ca_min_l12m,sa_min_l12m,sa_median_l12m,casa_min_l12m,sa_iqr_l12m,...,n_dpd_31_90_l3m,cons_delq_0_l3m,cons_delq_90_l3m,cons_delq_90_l12m,cons_delq_decrease_l12m,days_last_ptp_l1m,DIA_CHI,proba,score,score_bin
0,5/20/2024,202405,0,0.528738,NaN,203628.0,0.0,0.0,203628.0,0.0,...,0,0,0,0,0,8.0,1.0,0.022430,490.091849,"(453.07, 495.085]"
1,5/25/2024,202405,0,0.707115,NaN,401423.0,0.0,0.0,401423.0,0.0,...,0,0,0,0,0,NaN,0.0,0.017004,510.470105,"(495.085, 520.179]"
2,5/10/2024,202405,0,0.692592,NaN,217429.0,0.0,0.0,217429.0,0.0,...,0,0,0,0,0,19.0,0.0,0.014189,523.729345,"(520.179, 539.657]"
3,5/25/2024,202405,0,0.543745,NaN,5162.0,0.0,0.0,5162.0,0.0,...,0,0,0,0,0,NaN,0.0,0.007535,569.866377,"(556.129, 570.838]"
4,5/29/2024,202405,0,0.379496,NaN,465004.0,0.0,0.0,465004.0,0.0,...,0,0,0,0,1,0.0,NaN,0.033728,459.828319,"(453.07, 495.085]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111155,4/21/2023,202304,0,0.394103,0.750000,321814.0,0.0,0.0,321814.0,0.0,...,0,0,0,0,0,4.0,3.0,0.013692,526.336430,"(520.179, 539.657]"
111156,4/15/2023,202304,0,0.652208,0.900000,524207.0,0.0,0.0,524207.0,0.0,...,0,0,0,0,0,NaN,1.0,0.006040,585.931482,"(585.598, 601.957]"
111157,4/15/2023,202304,0,0.431215,0.600000,66668.0,0.0,0.0,66668.0,0.0,...,0,0,0,0,0,NaN,0.0,0.007459,570.604731,"(556.129, 570.838]"
111158,4/20/2023,202304,0,0.646248,0.562500,93353.0,0.0,0.0,93353.0,0.0,...,0,0,0,0,0,NaN,3.0,0.014497,522.159662,"(520.179, 539.657]"
111159,4/25/2023,202304,0,0.590668,1.294118,486927.0,0.0,0.0,486927.0,0.0,...,0,0,0,0,1,NaN,1.0,0.045554,437.257552,"(57.435, 453.07]"

In [83]:
cols = ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']

df_train_sub=df_train.loc[:,cols]

df_train_sub.to_csv('TUNGTT9_TMP_RECOVERY_PBL_TRAIN.csv',index=False)

In [84]:
cols = ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']

df_test_sub=df_test.loc[:,cols]

df_test_sub.to_csv('TUNGTT9_TMP_RECOVERY_PBL_TEST.csv',index=False)

In [85]:
cols = ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']
df_val_sub=df_val.loc[:,cols]

df_val_sub.to_csv('TUNGTT9_TMP_RECOVERY_PBL_VAL.csv',index=False)

# Feature analysis

In [87]:
df_train_sub = pd.read_csv('TUNGTT9_TMP_RECOVERY_PBL_TRAIN.csv',sep=',').reset_index(drop=True)

exclude_cols = ['MAKH','DATEIN_DATE', 'MONTHIN', 'TAG_GB']
cols = [col for col in df_train_sub.columns if col not in exclude_cols]

for col in cols:
    df_train_sub[f'{col}_bin'] = pd.qcut(df_train_sub[f'{col}'], 4, duplicates='drop')

In [88]:
df_train['repayment_percentage_l6m_bin'] = pd.qcut(df_train.repayment_percentage_l6m, 4, duplicates='drop')

repayment_percentage_l6m_pivot = df_train.pivot_table(index='repayment_percentage_l6m_bin', columns='TAG_GB', aggfunc='size', fill_value=0)
repayment_percentage_l6m_pivot['BAD_RATE'] = repayment_percentage_l6m_pivot[1]/(repayment_percentage_l6m_pivot[1]+repayment_percentage_l6m_pivot[0])
repayment_percentage_l6m_pivot=repayment_percentage_l6m_pivot.reset_index(drop=False)
# repayment_percentage_l6m_pivot
repayment_percentage_l6m_pivot.to_csv('repayment_percentage_l6m_pivot.csv', index=False)

AttributeError: 'DataFrame' object has no attribute 'repayment_percentage_l6m'

In [26]:
import pandas as pd

# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='age_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('age_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_3371/4245632668.py:4: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [24]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_amt_cv_l3m_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_amt_cv_l3m_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_20175/2825071196.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [27]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='repayment_percentage_l1m_bin',
    columns='m_since_max_payment_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('repayment_percentage_l1m_ct_m_since_max_payment_l6m.csv')

/tmp/ipykernel_3371/2728673713.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

m_since_max_payment_l6m_bin,"(-0.001, 1.0]","(1.0, 3.0]","(3.0, 4.0]","(4.0, 5.0]"
repayment_percentage_l1m_bin,,,,
"(-0.001, 1.0]",0.0595,0.0427,0.0381,0.0362

In [27]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='repayment_percentage_l3m_bin',
    columns='count_activity_cv_l3m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('repayment_percentage_l3m_ct_count_activity_cv_l3m.csv')

/tmp/ipykernel_20175/4237662857.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [29]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='total_ost_bin',
    columns='repayment_percentage_l3m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('total_ost_ct_repayment_percentage_l3m.csv')

/tmp/ipykernel_3371/3708890818.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

repayment_percentage_l3m_bin  (-0.001, 1.0]
total_ost_bin
(-0.00099979, 14.0]                  0.0492
(14.0, 44.0]                         0.0280
(44.0, 82.104]                       0.0151
(82.104, 11989.171]                  0.0079

In [33]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_amt_iqr_l6m_bin',
    columns='total_ost_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_amt_iqr_l6m_ct_total_ost.csv')

/tmp/ipykernel_3371/219964078.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [31]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='total_ost_bin',
    columns='age_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('total_ost_ct_age.csv')

/tmp/ipykernel_3371/1507466639.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [35]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='m_since_last_payment_l6m_bin',
    columns='m_since_max_payment_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('m_since_last_payment_l6m_ct_m_since_max_payment_l6m.csv')

/tmp/ipykernel_3371/2866174604.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [36]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_amt_min_l6m_bin',
    columns='total_ost_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('trans_in_amt_min_l6m_ct_total_ost.csv')

/tmp/ipykernel_3371/3382179354.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

total_ost_bin,"(-0.00099979, 14.0]","(14.0, 44.0]","(44.0, 82.104]","(82.104, 11989.171]"
trans_in_amt_min_l6m_bin,,,,
"(-0.001, 20333.209]",0.0782,0.0463,0.0234,0.0173

In [38]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='repayment_percentage_l6m_bin',
    columns='count_session_id_avg_l3m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('repayment_percentage_l6m_ct_count_session_id_avg_l3m.csv')

/tmp/ipykernel_20175/1094189453.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [38]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_num_median_l3m_bin',
    columns='age_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_num_median_l3m_ct_age.csv')

/tmp/ipykernel_3371/2972268290.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [40]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_amt_std_l3m_bin',
    columns='total_ost_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_amt_std_l3m_ct_total_ost.csv')

/tmp/ipykernel_3371/3221889833.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [42]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_amt_q75_l3m_bin',
    columns='dpd_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_amt_q75_l3m_ct_dpd.csv')

/tmp/ipykernel_3371/2115959963.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [43]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='repayment_percentage_l3m_bin',
    columns='m_since_last_payment_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('repayment_percentage_l3m_ct_m_since_last_payment_l6m.csv')

/tmp/ipykernel_3371/2275656235.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

m_since_last_payment_l6m_bin  (-0.001, 2.0]  (2.0, 4.0]  (4.0, 5.0]
repayment_percentage_l3m_bin
(-0.001, 1.0]                        0.0615      0.0216      0.0184

In [45]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='total_ost_bin',
    columns='m_since_max_payment_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('total_ost_ct_m_since_max_payment_l6m.csv')

/tmp/ipykernel_3371/4250675471.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [47]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_num_iqr_l6m_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_num_iqr_l6m_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_3371/3512435169.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [50]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_num_max_l6m_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_num_max_l6m_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_3371/2563301920.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [52]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_amt_max_l6m_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_amt_max_l6m_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_3371/1949542129.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [54]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_num_iqr_l6m_bin',
    columns='total_ost_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_num_iqr_l6m_ct_total_ost.csv')

/tmp/ipykernel_3371/1198992032.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [55]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_amt_min_l6m_bin',
    columns='dpd_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('trans_out_amt_min_l6m_ct_dpd.csv')

/tmp/ipykernel_3371/1492062497.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

dpd_bin,"(360.999, 495.0]","(495.0, 648.0]","(648.0, 954.0]","(954.0, 6355.0]"
trans_out_amt_min_l6m_bin,,,,
"(-0.001, 20325.764]",0.042,0.0434,0.0466,0.0348

In [56]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_num_min_l6m_bin',
    columns='age_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

pivot_table
# pivot_table.to_csv('trans_in_num_min_l6m_ct_age.csv')

/tmp/ipykernel_3371/372727902.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

age_bin,"(3.999, 28.0]","(28.0, 33.0]","(33.0, 39.0]","(39.0, 124.0]"
trans_in_num_min_l6m_bin,,,,
"(-0.001, 589.0]",0.044,0.0378,0.0389,0.0497

In [58]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_amt_iqr_l6m_bin',
    columns='repayment_percentage_l6m_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_amt_iqr_l6m_ct_repayment_percentage_l6m.csv')

/tmp/ipykernel_3371/2155377415.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [60]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='dpd_bin',
    columns='age_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('dpd_ct_age.csv')

/tmp/ipykernel_3371/3049566893.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [62]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_amt_std_l3m_bin',
    columns='dpd_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_amt_std_l3m_ct_dpd.csv')

/tmp/ipykernel_3371/635115357.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [65]:
df_train['age_bin'] = pd.qcut(df_train.age, 4, duplicates='drop')

age_pivot = df_train.pivot_table(index='age_bin', columns='tag_good_bad', aggfunc='size', fill_value=0)
age_pivot['BAD_RATE'] = age_pivot[1]/(age_pivot[1]+age_pivot[0])
age_pivot=age_pivot.reset_index(drop=False)
# age_pivot
age_pivot.to_csv('age_pivot.csv', index=False)

/tmp/ipykernel_3371/3057596293.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  age_pivot = df_train.pivot_table(index='age_bin', columns='tag_good_bad', aggfunc='size', fill_value=0)

In [67]:
df_train['trans_out_amt_iqr_l6m_bin'] = pd.qcut(df_train.trans_out_amt_iqr_l6m, 4, duplicates='drop')

trans_out_amt_iqr_l6m_pivot = df_train.pivot_table(index='trans_out_amt_iqr_l6m_bin', columns='tag_good_bad', aggfunc='size', fill_value=0)
trans_out_amt_iqr_l6m_pivot['BAD_RATE'] = trans_out_amt_iqr_l6m_pivot[1]/(trans_out_amt_iqr_l6m_pivot[1]+trans_out_amt_iqr_l6m_pivot[0])
trans_out_amt_iqr_l6m_pivot=trans_out_amt_iqr_l6m_pivot.reset_index(drop=False)
# trans_out_amt_iqr_l6m_pivot
trans_out_amt_iqr_l6m_pivot.to_csv('trans_out_amt_iqr_l6m_pivot.csv', index=False)

/tmp/ipykernel_3371/2359554724.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  trans_out_amt_iqr_l6m_pivot = df_train.pivot_table(index='trans_out_amt_iqr_l6m_bin', columns='tag_good_bad', aggfunc='size', fill_value=0)

In [68]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_in_num_iqr_l3m_bin',
    columns='age_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_in_num_iqr_l3m_ct_age.csv')

/tmp/ipykernel_3371/233617570.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(

In [70]:
# Calculate the bad rate pivot table
pivot_table = pd.pivot_table(
    df_train_sub,
    index='trans_out_num_iqr_l6m_bin',
    columns='dpd_bin',
    values='tag_good_bad',
    aggfunc=lambda x: (x == 1).sum() / len(x)
)

# Optional: format for clarity
pivot_table = pivot_table.round(4)

# pivot_table
pivot_table.to_csv('trans_out_num_iqr_l6m_ct_dpd.csv')

/tmp/ipykernel_3371/1374843707.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table = pd.pivot_table(